# Generated by Django 5.1.3 on 2024-11-15 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(default='#', max_length=100)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_menu', to='core.sidebar')),
            ],
            options={
                'db_table': 'sidebar',
            },
        ),
    ]
